apiVersion: v1
kind: ConfigMap
metadata:
  namespace: debug
  name: nginx
data:
  nginx.conf: |
    worker_processes 5;
    events {
    }
    http {
      # This is the main site.
      server {
        listen 80 default_server;
        listen 443 ssl;
        default_type text/plain;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        location / {
          return 200 "Hostname: $hostname\nUser: $remote_user\nProtocol: $server_protocol\nMethod: $request_method\nPath: $request_uri\nServer: $server_addr\nHttp_host: $http_host\nuser_agent: $http_user_agent\nRemote IP: $remote_addr\nX-Forwarded-For: $http_x_forwarded_for\nX-Forwarded-Proto: $http_x_forwarded_proto\nX-Forwarded-Port: $http_x_forwarded_port\ncookie: $http_cookie\n";	
        }

        location = /healthz {
          add_header Content-Type text/plain;
          return 200 'ok';
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: nginx-ssl
  namespace: debug
data:
  nginx.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVBakNDQXVxZ0F3SUJBZ0lRQUlzZWR1RHJNTDVHTGg1bFROK0xQVEFOQmdrcWhraUc5dzBCQVFzRkFEQjMKTVFzd0NRWURWUVFHRXdKS1VERU9NQXdHQTFVRUNCTUZWRzlyZVc4eEVqQVFCZ05WQkFjVENVMXBibUYwYnkxcgpkVEVQTUEwR0ExVUVDaE1HVmsxM1lYSmxNUXN3Q1FZRFZRUUxFd0pEVXpFbU1DUUdBMVVFQXhNZFdWVkxTU0JKClRsUkZVazFGUkVsQlZFVWdTVzUwWlhKdVlXd2dRMEV3SGhjTk1qQXdNVEE0TVRJd09ETTFXaGNOTkRjd05USTEKTVRJd09ETTBXakJ4TVFzd0NRWURWUVFHRXdKS1VERU9NQXdHQTFVRUNCTUZWRzlyZVc4eEVqQVFCZ05WQkFjVApDVTFwYm1GMGJ5MXJkVEVQTUEwR0ExVUVDaE1HVmsxM1lYSmxNUXN3Q1FZRFZRUUxFd0pEVXpFZ01CNEdBMVVFCkF4TVhkMmxzWkdOaGNtUXVZWEJ3TG1OdmNuQXViRzlqWVd3d2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDbFdHRnd0SHRDTDI5WUZlTktEUEJBdWIyaUtma0VDcld2ckZzS3JOVHNaZytBSjgxMwo0SEhNQ1I0ME1zWXhybGZmVXE4R0UyRDV3YTVKWUEwalZlcytqbFh0S3pqSWIyRThnNUZnV1JQQmNoWEJ1eXpkClFxL0ZGYy9BQmFSTmJqVDBST1Ztc2FLWkxUTCt3bk9YWlpIZElCdXh0eXFldklWeXRjbHVzdUowMXREdDQ4WWsKcVlWTjFnMDBCYW9NeWg4SGVZdXBsU3hybWNaRXVSNU45OGdHUHFnUXZ4UjcrWmpUSnJYdWsxa1VIVmhpV1IrbQpWbkgxV2YrYzM0cE1qSzZENW5NcjdUZmlUdVQ0TjV2QzFTVzlWbHRnUmFpbjNJZHpDVXpDeUVMZjVSRjNjY2ZJCjlRZGtqNEZnZklNUVA0SHY1NWNhWGZlNUlpQTZ2dXVSZDNqdkFnTUJBQUdqZ1k4d2dZd3dEZ1lEVlIwUEFRSC8KQkFRREFnV2dNQjBHQTFVZEpRUVdNQlFHQ0NzR0FRVUZCd01CQmdnckJnRUZCUWNEQWpBZEJnTlZIUTRFRmdRVQpXeEdkQjQ5VGh6d09pOGFjVGpmRVFhbjVSK0V3SHdZRFZSMGpCQmd3Rm9BVXE1ZHJVUzR6Z2g2SDFSc3l4eFJRCjRHREdnUVF3R3dZRFZSMFJCQlF3RW9JUUtpNWhjSEF1WTI5eWNDNXNiMk5oYkRBTkJna3Foa2lHOXcwQkFRc0YKQUFPQ0FRRUFUaFVYQUJ5RmhjeWpSVi9oYzB6ckVPWHlPZWJ4aHo4Y1ZYTlNTc3YybkxIWnp1RVM2RVJ4UGJ3ZQo2VHpoYjNHL3RqRGVicUN6VW9DUTZ3SnZLcmIwOEo3YkxQalM2aGt2anFlRVVpQkg0bWw4SDdOSGtaTzlhYkJoCkF4Mk1kWUFpUVd3Z0hxemdFQmE3bVhmenRMU1Vta3hmN3dDMHNzcFcyYXpHalBYOWw0cHZsa0ZtVFZCdHlSNy8KTWlpTWtiZklPanFKTnBxdFQxQ1ZOQmlEejZvMGtBL0dWei83bjdWVlpCczJTZVhoMjBVb2ZxbGlOazdWcm5JOAo2SmJlcXV0R2dXbUJzUHd6N1BtRkhOK1JnbUVMQkVhL0Zrb0liamZUaW84STN0UHVoUkhtcHJqVkVhNHJPdkJQClFDT1Z0SUZOdlJ2bXhmby9jVjZsaW92ckNVaisvdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
  nginx.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb2dJQkFBS0NBUUVBcFZoaGNMUjdRaTl2V0JYalNnendRTG05b2luNUJBcTFyNnhiQ3F6VTdHWVBnQ2ZOCmQrQnh6QWtlTkRMR01hNVgzMUt2QmhOZytjR3VTV0FOSTFYclBvNVY3U3M0eUc5aFBJT1JZRmtUd1hJVndic3MKM1VLdnhSWFB3QVdrVFc0MDlFVGxackdpbVMweS9zSnpsMldSM1NBYnNiY3FucnlGY3JYSmJyTGlkTmJRN2VQRwpKS21GVGRZTk5BV3FETW9mQjNtTHFaVXNhNW5HUkxrZVRmZklCajZvRUw4VWUvbVkweWExN3BOWkZCMVlZbGtmCnBsWng5Vm4vbk4rS1RJeXVnK1p6SyswMzRrN2srRGVid3RVbHZWWmJZRVdvcDl5SGN3bE13c2hDMytVUmQzSEgKeVBVSFpJK0JZSHlERUQrQjcrZVhHbDMzdVNJZ09yN3JrWGQ0N3dJREFRQUJBb0lCQUV0ajR2bjZzUURhbEJBNwoycWpYQVd6aHcvOSsxOVhwOURHbml0TnhQcHlUWkpud2pCVU90NVJxeStUTkNlVjVNd1BXdFlzMXBzLzZhYmQzCkhrWndWSlR2WFdxSWZKbVhmMlNTTU9VWGVKU0pxalh0WEdWK2xKcHVlWTE2aFJIeElDQUlrZmlqSWhwcHE0alIKck5icEx2citPdUpyTy9tb3g4Z243ektVU2dFdmZlS3RjTU40VGx4QUg3RURWSVo1V2ZVK2NRZjhnc3pWdVZaOApVUmtWZVRZRldUMUpCNllmNldmWi85YzlTQ2QrSHZTZ0lTRnFEdk0vUHpMNElhbTBjazhQLzN6T0FSb2NBTXlhCmw3clNDNVpMcXJMTFRTbWFQSlRSM1dFdkM5aXFWNk9rbWMyQmdibFpXTHlPUnJnMU11UkxIZDc4aGVUOGNrQjQKOU5UT0xWRUNnWUVBMHZaMkdONU9aUk1wTXkwSUFZVEFVK25nSWRnelR0YlFEZU9KMXYvYmdFY0hPYklCTHRvcQpxUFhNbnZ3YnRHM2t1VXhOd3BDZnRDSGVKZnZ2eHhtdEtwODg5c2MyUUYvUVRIWThnYmJBVHNMcWRKc3NUUGo1ClprWlN5R25ZMkdTaldjU2pCMHUrWWt2V2h4WjRlU1VOTUZ5UXBVVjZpc3VlcFBoOHRlMVdYVU1DZ1lFQXlLVFUKdFhDaU4zRHE0S0dkODVBcExlZlA0Vk1GdzJPS1NkaVQ2UktxNG5BRW9vNFV0UkJ5WFp3L1lWbUpSNEI5VjZGMApkMDNJanN5UFdFZ2k3NytwcWFrdjVkMGpJb3l1Q0R2VzE5MEVIUWxWb3NMSk5KTlMyL1lOTGVvS09NL3k0Wk1CCk4ycHNYZVd3SzRpREhIUWg5cDE3b0pTOExsTDZoTEViREFxckJPVUNnWUFlcmg4d3NLdmdBVEJkcysvVklMUkQKditDTHE0Q1N0NlRjVURvTW5Yc1RwY0RFUUVIeHlXS28zYzViVkxqR3ZiQ2t6aGNFODdsMkhmTEx2Vjc2cXA1SApjNDhQS0p1WU14Yjg5N2tHK0VmeGJHRmlnZXFvYXhFQ01ibjZVWUpxdmdBUG53eENsRjVrdHpqRXZwellxVzNJCm1iMmplMzQ5enkwTU91TVFKaXNJTndLQmdBMW1mTkpWWUhBbGVYcGhNT1JvZDJlYWVOYktyYkxiL2d0cWpJNWYKY2N4SHdQZCtWOEcwQkg5ZUJSbWlXam5OU2hIRk5ic1dGZFA3czRNbzVqUnU3NHptUU0yd1ZEMWxlZVlRNFF0dgp0bXVlQ1BzaTJUOUtxNWtIT09BZEptdWU3OURDK2F6U3pjUURxQjF3TTVsOTVCck5iOGxNeGJpdVVBNzJxU0RICndaNUZBb0dBQkViV1lNYWtHQlA5a3gvcHlRZUhqaTlRaFhFRWczVjlhWUlMdmZPQ29VOWRwTTRBNkRFeXJ2U0cKb1gvUEJoOEtpemRLYlBhb29EU3c0ZXdYYWpBT3QyWjAyc0k2QmdaL2RkMHhnQmdvS3diaHp5bUdWQy80bUhyVwpBSWpmY3JVbHVRMnNTU0xZSVlIckUxd1V2V3BYQU1KZ2tDeTBlOVdJSDU4ZVlaRXd0bm89Ci0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debug-nginx
  namespace: debug
  labels:
    app: debug-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: debug-nginx
  template:
    metadata:
      labels:
        app: debug-nginx
    spec:
      containers:
      - name: debug-nginx
        image: ytsuboi/debug-nginx 
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 2
          failureThreshold: 2
        volumeMounts:
        - name: nginx
          mountPath: /etc/nginx
          readOnly: true
        - mountPath: /etc/nginx/ssl
          name: nginx-ssl
      volumes:
      - name: nginx
        configMap:
          name: nginx
      - name: nginx-ssl
        secret:
          secretName: nginx-ssl