apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-tls-ingress
  namespace: test
  labels:
    feature: tls-ingress   
spec:
  tls:
  - hosts:
    - tls-ingress2.demo.corp.local
    secretName: tls-ingress
  rules:
  - host: tls-ingress2.demo.corp.local
    http:
      paths:
      - path: "/"
        backend:
          serviceName: nginx-tls-ingress
          servicePort: 80
