apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: net-a
  namespace: ncp-feature  
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "nsx",
    "networkID": "seg-2nd-interface",
    "ipam": {
      "subnet": "192.168.0.0/24",
      "rangeStart": "192.168.0.2",
      "rangeEnd": "192.168.0.254",
      "gateway": "192.168.0.1"
    }
  }'
