apiVersion: v1
kind: ConfigMap
metadata:
  namespace: ncp-feature
  name: nginx
data:
  nginx.conf: |
    worker_processes 5;
    events {
    }
    http {
      # This is the main site.
      server {
        listen 80 default_server;
        listen 443 ssl;
        default_type text/plain;
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        location / {
<<<<<<< HEAD
          return 200 "Hostname: $hostname\nUser: $remote_user\nProtocol: $server_protocol\nMethod: $request_method\nPath: $request_uri\nServer: $server_addr\nHttp_host: $http_host\nuser_agent: $http_user_agent\nRemote IP: $remote_addr\nX-Forwarded-For: $http_x_forwarded_for\ncookie: $http_cookie\n";
=======
          return 200 "Hostname: $hostname\nUser: $remote_user\nProtocol: $server_protocol\nMethod: $request_method\nPath: $request_uri\nServer: $server_addr\nHttp_host: $http_host\nuser_agent: $http_user_agent\nRemote IP: $remote_addr\nX-Forwarded-For: $http_x_forwarded_for\nX-Forwarded-Proto: $http_x_forwarded_proto\nX-Forwarded-Port: $http_x_forwarded_port\ncookie: $http_cookie\n";
>>>>>>> d38532972ba403d0ebb4e19328792ed95c89fd48
        }

        location = /healthz {
          add_header Content-Type text/plain;
          return 200 'ok';
        }
      }
    }
