apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-ingress-rc-nat
  labels:
    app: nginx-ingress-rc-nat
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-ingress-rc-nat
    spec:
      containers:
      - image: nginx/nginx-ingress:latest
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - containerPort: 80
          hostPort: 10080
        - containerPort: 443
          hostPort: 10443
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
          - -default-server-tls-secret=$(POD_NAMESPACE)/default-server-secret

