apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsx-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nsxdemo
  template:
    metadata:
      labels:
        app: nsxdemo
    spec:
      containers:
      - name: nsx-demo
        image: yfauser/nsx-demo
        ports:
        - containerPort: 80
